- name: "source1"
  bucket: "source-1"
  prefix: ""
  bucketUrl: ""
  mapping:
    id: "id"
    name: "name"
    city: "address.city"
    country: "address.country"
    isAvailable: "isAvailable"
    pricePerNight: "priceForNight"

- name: "source2"
  bucket: "source-2"
  prefix: ""
  bucketUrl: ""
  mapping:
    id: "id"
    city: "city"
    isAvailable: "availability"
    pricePerNight: "pricePerNight"
    priceSegment: "priceSegment"