- name: "source1"
  bucket: "source-1"
  prefix: "s1"
  bucketUrl: "https://buenro-tech-assessment-materials.s3.eu-north-1.amazonaws.com/structured_generated_data.json"
  mapping:
    id: "id"
    name: "name"
    city: "address.city"
    country: "address.country"
    isAvailable: "isAvailable"
    pricePerNight: "priceForNight"

- name: "source2"
  bucket: "source-2"
  prefix: "s2"
  bucketUrl: "https://buenro-tech-assessment-materials.s3.eu-north-1.amazonaws.com/large_generated_data.json"
  mapping:
    id: "id"
    city: "city"
    isAvailable: "availability"
    pricePerNight: "pricePerNight"
    priceSegment: "priceSegment"